// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/expenses": {
    params: {};
  };
  "/expenses/new": {
    params: {};
  };
  "/stats": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/expenses" | "/expenses/new" | "/stats";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/expenses.tsx": {
    id: "routes/expenses";
    page: "/expenses";
  };
  "routes/expenses-new.tsx": {
    id: "routes/expenses-new";
    page: "/expenses/new";
  };
  "routes/stats.tsx": {
    id: "routes/stats";
    page: "/stats";
  };
};