export const data = {
  users: [
    {
      user_id: 1,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      user_budget: 2000,
    },
    {
      user_id: 2,
      name: "Bob Smith",
      email: "bob.smith@example.com",
      user_budget: 3000,
    },
    {
      user_id: 3,
      name: "Charlie Lee",
      email: "charlie.lee@example.com",
      user_budget: 4000,
    },
    {
      user_id: 4,
      name: "Diana Brown",
      email: "diana.brown@example.com",
      user_budget: 3500,
    },
    {
      user_id: 5,
      name: "Ethan Davis",
      email: "ethan.davis@example.com",
      user_budget: 4500,
    },
  ],

  categories: [
    {
      1: "Groceries",
      2: "Entertainment",
      3: "Transportation",
      4: "Utilities",
      5: "Rent",
      6: "Salary",
      7: "Bills",
    },
  ],

  transactions: [
    {
      transaction_id: 1,
      user_id: 1,
      category_id: 6,
      amount: 2000,
      date: "2025-08-01",
      description: "Salary",
      type: "income",
    },
    {
      transaction_id: 2,
      user_id: 1,
      category_id: 2,
      amount: 50,
      date: "2025-08-03",
      description: "Movie night with friends",
      type: "expense",
    },
    {
      transaction_id: 33,
      user_id: 1,
      category_id: 3,
      amount: 30,
      date: "2025-08-05",
      description: "Taxi fare to office",
      type: "expense",
    },
    {
      transaction_id: 3,
      user_id: 1,
      category_id: 3,
      amount: 30,
      date: "2025-08-11",
      description: "Taxi fare to water park",
      type: "expense",
    },
    {
      transaction_id: 4,
      user_id: 2,
      category_id: 4,
      amount: 90,
      date: "2025-08-02",
      description: "Grocery shopping at Target",
      type: "expense",
    },
    {
      transaction_id: 5,
      user_id: 2,
      category_id: 5,
      amount: 60,
      date: "2025-08-04",
      description: "Electricity bill",
      type: "expense",
    },
    {
      transaction_id: 6,
      user_id: 2,
      category_id: 6,
      amount: 25,

      date: "2025-08-06",
      description: "Gym membership fee",
      type: "expense",
    },
    {
      transaction_id: 7,
      user_id: 3,
      category_id: 7,
      amount: 1500,
      date: "2025-08-01",
      description: "Monthly rent payment",
      type: "expense",
    },
  ],
};
